using './main.bicep'

param location = 'eastus2'
param logAnalyticsWorkspaceName = 'log-oh-rfp'
param managedIdentityName = 'id-oh-rfp-web'
param appServicePlanName = 'plan-oh-rfp'
param functionAppName = 'func-oh-rfp-approver'
param staticWebAppName = 'swa-oh-rfp-approver'
param aiProjectEndpoint = 'https://ohsupparfp-resource.services.ai.azure.com/api/projects/ohsupparfp'
param aiAgentName = 'oh-rfpApprover1'
param aiSearchServiceName = 'aisearch-ohsupparfp'
param aiSearchIndexName = 'rfp-index'
param storageAccountName = 'stohrfpapprover'
