using './main.bicep'

param location = 'centralus'
param logAnalyticsWorkspaceName = 'log-oh-rfp-cu'
param managedIdentityName = 'id-oh-rfp-web-cu'
param appServicePlanName = 'plan-oh-rfp-cu'
param functionAppName = 'func-oh-rfp-approver-cu'
param botServiceName = 'bot-oh-rfp-approver-cu'
param botMicrosoftAppId = '4454ce98-e46b-4e64-987c-53c73beca457'
param aiProjectEndpoint = 'https://ohsupparfp-resource.services.ai.azure.com/api/projects/ohsupparfp'
param aiAgentName = 'oh-rfpApprover1'
param aiSearchServiceName = 'aisearch-ohsupparfp'
param aiSearchIndexName = 'rfp-index'
param storageAccountName = 'stohrfpapprovercu1'
